-- Column drop for the shared-vendor-profile cutover (see
-- business/2026-07-21-profile-settings-page-standard.md, and the shared
-- schema itself: docs/superpowers/specs/2026-07-16-shared-vendor-profile-design.md).
--
-- loopkit.vendors.name was the pre-cutover local stall-name column, written
-- from two places: /dashboard/profile's save action and the phone-onboarding
-- login flow (vendorPhoneOnboardAction). Both now write the vendor's stall
-- name to the shared merqo.vendor_profile row (via upsert_vendor_profile)
-- instead, so this column is dead.
--
-- Per the locked spec's migration sequencing (business doc §3.4), a column
-- drop is normally a SEPARATE, LATER migration, run after a deploy
-- verification window following the code swap — not bundled into the same
-- PR. Bundled here instead per explicit product decision to cut over
-- immediately rather than wait.
--
-- loopkit.vendors itself is NOT dropped — it still holds `phone` (reserved
-- for the vendor-phone-onboarding spec) and its RLS/primary-key shape is
-- depended on by later migrations (see 0017_loopkit_vendor_profile.sql:
-- "Do not let a later migration re-create loopkit.vendors"). Only the one
-- column goes.
--
-- Manual review checklist (SQL migrations are hand-verified, not
-- automated-tested — see docs/CONSTITUTION.md §4):
--   [ ] Confirm no remaining app code selects/writes loopkit.vendors.name
--       (grep for `.from("vendors")` and `.select("name")`) before applying.
--   [ ] Confirm this migration is applied to the shared Supabase project
--       AFTER the code swap in this PR is deployed, not before (a mid-flight
--       old deployment still reading/writing `name` would error otherwise).
--   [ ] src/lib/types.ts has been hand-updated to drop `name` from the
--       `vendors` table's Row/Insert/Update shapes (no live DB codegen in
--       this repo yet — see supabase/migrations/README.md).
alter table loopkit.vendors drop column name;
